[[buildpacks]]
id = "make"
version = "0.0.1"
uri = "../../buildpacks/make"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/node-engine:1.3.0"
version = "1.3.0"

[[buildpacks]]
uri = "docker://gcr.io/paketo-buildpacks/go-dist:2.3.0"
version = "2.3.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "1.3.0"

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "2.3.0"

  [[order.group]]
    id = "make"
    version = "0.0.1"

[stack]
id = "io.buildpacks.stacks.bionic"
build-image = "ghcr.io/enrichman/bionic-full-stack-build:0.1.0"
run-image = "ghcr.io/enrichman/bionic-full-stack-run:0.1.0"
